import os
import sys
import json
import argparse

sys.stdout.reconfigure(encoding="utf-8")
import re
from google_auth_oauthlib.flow import InstalledAppFlow
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

ROOT = os.path.dirname(os.path.abspath(__file__))
TOKEN_PATH = os.path.join(ROOT, "..", "token.json")
SECRETS_PATH = os.path.join(ROOT, "..", "client_secrets.json")
SCOPES = ["https://www.googleapis.com/auth/youtube"]

def get_authenticated_service():
    creds = None
    if os.path.exists(TOKEN_PATH):
        with open(TOKEN_PATH) as f:
            data = json.load(f)
        creds = Credentials.from_authorized_user_info(data, SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(SECRETS_PATH, SCOPES)
            creds = flow.run_local_server(port=8080)
            with open(TOKEN_PATH, "w") as f:
                f.write(creds.to_json())

    return build("youtube", "v3", credentials=creds)

def upload_video(video_path, title, description="", tags=None, privacy="public"):
    if not os.path.exists(video_path):
        print(f"Video file not found: {video_path}")
        return None

    print("Authenticating with YouTube API...")
    youtube = get_authenticated_service()
    size = os.path.getsize(video_path)
    print(f"Uploading: {os.path.basename(video_path)} ({size // 1024 // 1024}MB)")

    body = {
        "snippet": {
            "title": title[:100],
            "description": description[:5000],
            "tags": (tags or [])[:500],
            "categoryId": "10",
        },
        "status": {"privacyStatus": privacy},
    }

    media = MediaFileUpload(video_path, chunksize=4 * 1024 * 1024, resumable=True)
    request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)

    response = None
    last_progress = 0
    while response is None:
        status, response = request.next_chunk()
        if status:
            progress = int(status.progress() * 100)
            if progress >= last_progress + 10:
                print(f"  Progress: {progress}%")
                last_progress = progress

    video_id = response.get("id", "?")
    print(f"✅ Upload successful! Link: https://youtu.be/{video_id}")
    return video_id

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--video", required=True)
    parser.add_argument("--title", required=True)
    parser.add_argument("--genre", default="Psytrance")
    args = parser.parse_args()

    description = (
        f"A traditional hymn remix reimagined as {args.genre.lower()} using AI-powered generation.\n\n"
        "Generated by HymnMania — transforming hymns into modern electronic music.\n"
        "Audio: Suno AI | Visualizer: Real MilkDrop via projectM 4.1.0\n"
        f"\nTrack: {args.title}\n"
    )

    tags = ["hymn", args.genre.lower(), "electronic", "ai music", "hymnmania", "milkdrop"]
    upload_video(args.video, args.title, description, tags)

if __name__ == "__main__":
    main()
